Repository playcanvas/developer-site, pull requests merged in 2020-12, with the labels that each got.

#187 Broken link checker
  .gitignore
  README.md
  package-lock.json
  package.json
  test-links.js
Labels: enhancement

#186 Add migration guide for legacy script projects
  content/en/user-manual/scripting/migration-guide.md
  public/images/user-manual/scripting/migration-guide/copy-assets.png
  public/images/user-manual/scripting/migration-guide/dashboard-warning.png
  public/images/user-manual/scripting/migration-guide/delete-script-components.png
  public/images/user-manual/scripting/migration-guide/download-scripts.png
  public/images/user-manual/scripting/migration-guide/editor-warning.png
  public/images/user-manual/scripting/migration-guide/select-script-entities.png
Labels: enhancement

#191 [FIX] Broken links
  content/en/tutorials/Using-forces-on-rigid-bodies.md
  content/en/tutorials/audio-effects.md
  content/en/tutorials/custom-posteffect.md
  content/en/tutorials/keepyup-part-five.md
  content/en/tutorials/keepyup-part-four.md
  content/en/tutorials/keepyup-part-one.md
  content/en/tutorials/keepyup-part-six.md
  content/en/tutorials/keepyup-part-three.md
  content/en/tutorials/keepyup-part-two.md
  content/en/tutorials/more-cameras.md
  content/en/user-manual/2D/sprite-editor.md
  content/en/user-manual/introduction.md
  content/en/user-manual/publishing/web/index.md
  content/en/user-manual/publishing/web/kongregate.md
  content/en/user-manual/scripting/debugging.md
  content/en/user-manual/xr/optimizing-webxr.md
  lib/locale/index.js
  lib/tutorials/index.js
  package-lock.json
Labels: bug

#193 Migrate request to node-fetch
  lib/tutorials/index.js
  package-lock.json
  package.json
Labels: enhancement

#198 Add some missing img alt attributes and update component images
  content/en/user-manual/assets/models/building.md
  content/en/user-manual/assets/models/exporting.md
  content/en/user-manual/assets/models/index.md
  content/en/user-manual/assets/models/units.md
  content/en/user-manual/packs/components/audiolistener.md
  content/en/user-manual/packs/components/button.md
  content/en/user-manual/packs/components/collision.md
  content/en/user-manual/packs/components/element.md
  content/en/user-manual/packs/components/scrollbar.md
  content/en/user-manual/packs/components/scrollview.md
  content/en/user-manual/packs/components/sound.md
  content/en/user-manual/packs/components/sprite.md
  public/images/user-manual/assets/models/building/blender-logo.jpg
  public/images/user-manual/assets/models/units/max-units.png
  public/images/user-manual/assets/models/units/maya-units.png
  public/images/user-manual/scenes/components/component-animation.png
  public/images/user-manual/scenes/components/component-audio-listener.png
  public/images/user-manual/scenes/components/component-audio-source.png
  public/images/user-manual/scenes/components/component-audiolistener.png
  public/images/user-manual/scenes/components/component-button-sprite-change.png
  public/images/user-manual/scenes/components/component-button-swap.jpg
  public/images/user-manual/scenes/components/component-button-tint.jpg
  public/images/user-manual/scenes/components/component-button-tint.png
  public/images/user-manual/scenes/components/component-camera.png
  public/images/user-manual/scenes/components/component-collision-box.png
  public/images/user-manual/scenes/components/component-collision-capsule.png
  public/images/user-manual/scenes/components/component-collision-compound.png
  public/images/user-manual/scenes/components/component-collision-cone.png
  public/images/user-manual/scenes/components/component-collision-cylinder.png
  public/images/user-manual/scenes/components/component-collision-mesh.png
  public/images/user-manual/scenes/components/component-collision-sphere.png
  public/images/user-manual/scenes/components/component-element-group.jpg
  public/images/user-manual/scenes/components/component-element-group.png
  public/images/user-manual/scenes/components/component-element-image.jpg
  public/images/user-manual/scenes/components/component-element-image.png
  public/images/user-manual/scenes/components/component-element-text.jpg
  public/images/user-manual/scenes/components/component-element-text.png
  public/images/user-manual/scenes/components/component-layoutchild.png
  public/images/user-manual/scenes/components/component-layoutgroup.png
  public/images/user-manual/scenes/components/component-light-directional.png
  public/images/user-manual/scenes/components/component-light-point.png
  public/images/user-manual/scenes/components/component-light-spot.png
  public/images/user-manual/scenes/components/component-model.png
  public/images/user-manual/scenes/components/component-particle-system.png
  public/images/user-manual/scenes/components/component-rigid-body-dynamic.png
  public/images/user-manual/scenes/components/component-rigid-body-kinematic.png
  public/images/user-manual/scenes/components/component-rigid-body-static.png
  public/images/user-manual/scenes/components/component-screen.png
  public/images/user-manual/scenes/components/component-script-attributes.png
  public/images/user-manual/scenes/components/component-script.png
  public/images/user-manual/scenes/components/component-scrollbar.png
  public/images/user-manual/scenes/components/component-scrollview.png
  public/images/user-manual/scenes/components/component-sound.png
  public/images/user-manual/scenes/components/component-sprite-animated.jpg
  public/images/user-manual/scenes/components/component-sprite-animated.png
  public/images/user-manual/scenes/components/component-sprite-simple.jpg
  public/images/user-manual/scenes/components/component-sprite-simple.png
  templates/intro.tmpl.html
  templates/partials/footer.tmpl.html
  templates/partials/header.tmpl.html
Labels: enhancement

#203 Fix sass command and remove hidden element
  package.json
  public/css/styles.css
  sass/styles.scss
  templates/partials/header.tmpl.html
Labels: bug

#205 Image tidy ups
  content/en/user-manual/assets/models/building.md
  public/images/artist_guide/max_material_editor.psd
  public/images/artist_guide/maya_material_editor.psd
  public/images/artist_guide/visualizer.jpg
  public/images/artist_guide/visualizer_menu_max.jpg
  public/images/artist_guide/visualizer_menu_maya.jpg
  public/images/common/BANNER_STRIPS1_Purp.png
  public/images/common/HOME_CHEVRON.png
  public/images/common/HOME_CHEVRON@x2.png
  public/images/common/loader.gif
  public/images/common/tick.png
  public/images/headings/api.png
  public/images/headings/art.png
  public/images/headings/designer.png
  public/images/headings/engine.png
  public/images/headings/publishing.png
  public/images/user-manual/assets/models/building/max-material-editor.jpg
  public/images/user-manual/assets/models/building/maya-material-editor.jpg
  public/images/user-manual/assets/models/building/mountains-sphere.jpg
  public/images/user-manual/assets/models/building/wall-norm-yflip.jpg
  public/images/user-manual/assets/models/building/wall-norm.jpg
Labels: enhancement

#208 Fix and update glossary
  content/en/user-manual/assets/animation.md
  content/en/user-manual/assets/models/index.md
  content/en/user-manual/glossary.md
  content/en/user-manual/graphics/physical-rendering/physical-materials.md
Labels: bug, enhancement
