Repository playcanvas/developer-site, pull requests merged in 2023-02, with the labels that each got.

#472 Fix various HTML errors
  build.js
  content/en/tutorials/crash-course.md
  content/en/tutorials/importing-first-model-and-animation.md
  content/en/tutorials/real-time-multiplayer-photon.md
  content/en/tutorials/ui-text-input.md
  content/en/user-manual/assets/models/units.md
  content/en/user-manual/faq.md
  content/en/user-manual/graphics/shader-chunk-migrations.md
  content/en/user-manual/physics/compound-shapes.md
  content/en/user-manual/scripting/anatomy.md
  content/en/user-manual/scripting/application-lifecyle.md
  content/en/user-manual/scripting/code-editor.md
  content/en/user-manual/user-interface/index.md
  content/en/user-manual/user-interface/user-interface-basics.md
  content/en/user-manual/xr/ar/8th-wall-integration.md
  faq/create_shape.md
  package-lock.json
  package.json
Labels: bug

#473 Lint HTML
  .github/workflows/ci.yml
  .htmlvalidate.json
  build.js
  content/en/user-manual/assets/materials/index.md
  content/en/user-manual/assets/materials/phong-material.md
  content/en/user-manual/assets/materials/physical-material.md
  content/en/user-manual/assets/textures/texture-compression.md
  package.json
Labels: enhancement

#476 Update to latest Metalsmith Layouts plugin
  build.js
  lib/i18n/index.js
  lib/tutorials/index.js
  package-lock.json
  package.json
Labels: enhancement

#480 Added warning on using old engine versions in launch tab
  content/en/user-manual/scripting/custom_engine.md
Labels: bug

#481 faq translated to Russian
  content/en/user-manual/faq.md
  content/ru/user-manual/faq.md
Labels: enhancement

#482 Switch controls page to use Markdown instead of HTML
  content/en/user-manual/designer/keyboard-shortcuts.md
Labels: enhancement

#483 profile section is translated to Russian
  content/ru/user-manual/creating-account.md
  content/ru/user-manual/dashboard/settings.md
  content/ru/user-manual/made-with-playcanvas.md
  content/ru/user-manual/profile/home.md
  content/ru/user-manual/profile/index.md
  content/ru/user-manual/profile/projects.md
Labels: enhancement, translation

#487 Upgrade build process to ES Modules
  build.mjs
  lib/contents-json/index.mjs
  lib/i18n-out/index.mjs
  lib/i18n/index.mjs
  lib/locale/index.mjs
  lib/nav-builder-plugin/index.mjs
  lib/tutorials/index.mjs
  package.json
Labels: enhancement

#488 Set background color of developer site to white
  public/css/styles.css
  sass/_variables.scss
  sass/styles.scss
Labels: bug

#496 Remove px from img attributes
  content/en/tutorials/basic-materials.md
  content/en/tutorials/collision-and-triggers.md
  content/en/tutorials/light-halos.md
  content/en/tutorials/real-time-multiplayer.md
  content/en/tutorials/ui-elements-buttons.md
  content/en/tutorials/using-assets.md
  content/en/user-manual/assets/import-pipeline/import-hierarchy.md
  content/en/user-manual/assets/import-pipeline/index.md
  content/en/user-manual/packs/components/script.md
  content/en/user-manual/packs/index.md
  content/en/user-manual/publishing/playable-ads/fb-playable-ads.md
  content/en/user-manual/publishing/playable-ads/ironsource-mraid-playable-ads.md
  content/en/user-manual/publishing/playable-ads/snapchat-playable-ads.md
  content/en/user-manual/user-interface/safe-area.md
Labels: bug

#493 Added GLB import information and new asset tasks (Draco + FBX folder)
  content/en/user-manual/assets/import-pipeline/import-hierarchy.md
  content/en/user-manual/assets/import-pipeline/index.md
  content/en/user-manual/assets/models/building.md
  content/en/user-manual/assets/models/exporting.md
  content/en/user-manual/assets/models/index.md
  public/images/user-manual/assets/import-pipeline/asset-tasks-full.jpg
  public/images/user-manual/assets/import-pipeline/asset-tasks.png
  public/images/user-manual/assets/import-pipeline/draco-import-button.png
  public/images/user-manual/assets/models/building/glb-import.gif
Labels: enhancement

#494 Asset viewers and animation previews
  content/en/user-manual/assets/animation.md
  content/en/user-manual/assets/viewers.md
  public/images/user-manual/assets/animation/anim-state-graph-preview.gif
  public/images/user-manual/assets/animation/inspector-preview.gif
  public/images/user-manual/assets/viewers/model-viewer-preview.jpg
  public/images/user-manual/assets/viewers/open-in-viewer-option.jpg
  public/images/user-manual/assets/viewers/texture-tool-preview.jpg
Labels: enhancement

#495 Updated light shadow options and add shadow intensity
  content/en/user-manual/graphics/lighting/shadows.md
  public/images/user-manual/graphics/lighting/shadows/light-shadow-options.png
  public/images/user-manual/graphics/lighting/shadows/shadow-intensity.gif
Labels: enhancement
