Repository playcanvas/developer-site, pull requests merged in 2024-02, with the labels that each got.

#569 Update social card
  docusaurus.config.js
  static/img/docusaurus-social-card.jpg
  static/img/playcanvas-social-card.jpg
Labels: enhancement

#572 Add CNAME
  static/CNAME
Labels: bug, docs

#576 Add support for query strings in tutorials section
  src/pages/tutorials.js
Labels: enhancement

#582 WebXR Depth Sensing - User Manual
  docs/user-manual/xr/ar/depth-sensing.md
  docs/user-manual/xr/capabilities.md
Labels: enhancement, docs

#586 Update Actions to use main
  .github/workflows/deploy.yml
  .github/workflows/test-deploy.yml
Labels: enhancement

#587 Move location of custom engine page
  .tx/config
  docs/user-manual/editor/launch-page/custom-engine.md
  docs/user-manual/editor/launch-page/index.md
  docs/user-manual/editor/launch-page/loading-screen.md
  docs/user-manual/editor/settings.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/launch-page/custom-engine.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/launch-page/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/launch-page/loading-screen.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/settings.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/anchors.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/camera-color.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/depth-sensing.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/dom-overlay.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/capabilities.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/input-sources.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/optimizing-webxr.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/using-webxr.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/vr/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/vr/types-of-vr.md
Labels: enhancement

#588 WebXR user manual categories rearrangements
  docs/user-manual/xr/ar/index.md
  docs/user-manual/xr/capabilities.md
  docs/user-manual/xr/hand-tracking.md
  docs/user-manual/xr/index.md
  docs/user-manual/xr/input-sources.md
  docs/user-manual/xr/optimizing-webxr.md
  docs/user-manual/xr/using-webxr.md
  docs/user-manual/xr/vr/index.md
Labels: enhancement, docs

#589 WebXR Hit Testing - User Manual
  docs/user-manual/xr/ar/anchors.md
  docs/user-manual/xr/ar/hit-testing.md
  docs/user-manual/xr/capabilities.md
Labels: enhancement, docs

#592 Add docs on advanced hierarchy search
  docs/user-manual/editor/hierarchy.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/hierarchy.md
  static/images/user-manual/editor/hierarchy.png
  static/images/user-manual/editor/hierarchy/hierarchy-panel.png
  static/images/user-manual/editor/hierarchy/hierarchy-search-options.png
  static/images/user-manual/editor/hierarchy/hierarchy-search.png
Labels: enhancement, docs

#593 Add new page on the Editor Toolbar
  .tx/config
  docs/user-manual/editor/menus-and-toolbar.md
  docs/user-manual/editor/settings.md
  docs/user-manual/editor/toolbar.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/menus-and-toolbar.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/settings.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/toolbar.md
  static/images/user-manual/editor/toolbar/code-editor.png
  static/images/user-manual/editor/toolbar/controls.png
  static/images/user-manual/editor/toolbar/feedback.png
  static/images/user-manual/editor/toolbar/focus.png
  static/images/user-manual/editor/toolbar/how-do-i.png
  static/images/user-manual/editor/toolbar/lightmapper.png
  static/images/user-manual/editor/toolbar/menu.png
  static/images/user-manual/editor/toolbar/publish.png
  static/images/user-manual/editor/toolbar/redo.png
  static/images/user-manual/editor/toolbar/resize-element.png
  static/images/user-manual/editor/toolbar/rotate.png
  static/images/user-manual/editor/toolbar/scale.png
  static/images/user-manual/editor/toolbar/settings.png
  static/images/user-manual/editor/toolbar/snap.png
  static/images/user-manual/editor/toolbar/translate.png
  static/images/user-manual/editor/toolbar/undo.png
  static/images/user-manual/editor/toolbar/world-local.png
Labels: enhancement, docs

#595 Add more admonitions to various pages
  docs/user-manual/assets/importing.md
  docs/user-manual/assets/types/cubemap.md
  docs/user-manual/templates/index.md
  docs/user-manual/user-interface/image-elements.md
  docs/user-manual/user-interface/text-elements.md
  docs/user-manual/version-control/branches.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/importing.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/types/cubemap.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/templates/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/user-interface/image-elements.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/user-interface/text-elements.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/version-control/branches.md
Labels: enhancement, docs

#596 Split Settings into Editor and Scene
  .tx/config
  docs/user-manual/assets/types/texture-atlas.md
  docs/user-manual/editor/assets.md
  docs/user-manual/editor/editor-api.md
  docs/user-manual/editor/keyboard-shortcuts.md
  docs/user-manual/editor/settings.md
  docs/user-manual/editor/viewport.md
  docs/user-manual/faq.md
  docs/user-manual/graphics/advanced-rendering/batching.md
  docs/user-manual/graphics/lighting/runtime-lightmaps.md
  docs/user-manual/publishing/web/playcanvas-hosting.md
  docs/user-manual/scenes/components/collision.md
  docs/user-manual/scenes/index.md
  docs/user-manual/scenes/loading-scenes.md
  docs/user-manual/scenes/managing-scenes.md
  docs/user-manual/scenes/settings.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/types/texture-atlas.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/assets.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/settings.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/viewport.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/faq.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/advanced-rendering/batching.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/lighting/runtime-lightmaps.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/web/playcanvas-hosting.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/components/collision.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/loading-scenes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/managing-scenes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/settings.md
  static/images/user-manual/editor/settings/editor-settings.png
  static/images/user-manual/scenes/managing-scenes/scenes-menu.jpg
  static/images/user-manual/scenes/managing-scenes/scenes-viewport.jpg
  static/images/user-manual/scenes/managing-scenes/scenes.jpg
  static/images/user-manual/scenes/settings/cog.jpg
  static/images/user-manual/scenes/settings/gamma-correction.jpg
  static/images/user-manual/scenes/settings/lightmapping-settings.png
Labels: enhancement, docs

#597 Move post effect images into correct folder
  docs/user-manual/graphics/posteffects/bloom.md
  docs/user-manual/graphics/posteffects/brightness_contrast.md
  docs/user-manual/graphics/posteffects/fxaa.md
  docs/user-manual/graphics/posteffects/hue_saturation.md
  docs/user-manual/graphics/posteffects/sepia.md
  docs/user-manual/graphics/posteffects/vignette.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/posteffects/bloom.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/posteffects/brightness_contrast.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/posteffects/fxaa.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/posteffects/hue_saturation.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/posteffects/sepia.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/posteffects/vignette.md
  static/images/user-manual/graphics/posteffects/with-bloom.png
  static/images/user-manual/graphics/posteffects/with-brightness-contrast.png
  static/images/user-manual/graphics/posteffects/with-fxaa.png
  static/images/user-manual/graphics/posteffects/with-hue-saturation.png
  static/images/user-manual/graphics/posteffects/with-sepia.png
  static/images/user-manual/graphics/posteffects/with-vignette.png
  static/images/user-manual/graphics/posteffects/without-effects.png
Labels: enhancement

#598 Delete unused images
  static/images/common/BANNER_STRIPS1_Orange.png
  static/images/common/flags/China.png
  static/images/common/flags/Japan.png
  static/images/common/flags/Russia.png
  static/images/common/flags/United-Kingdom.png
  static/images/header/PLAYCANVAS__ICON_CLEARflat.png
  static/images/header/PLAYCANVAS__ICON_CLEARflat@x2.png
  static/images/header/PLAYCANVAS__LOGOTEXT.png
  static/images/header/PLAYCANVAS__LOGOTEXT@x2.png
  static/images/header/PLAYMANUAL.png
  static/images/header/playcanvas-icon-80.png
  static/images/platform/bitbucket_code_repo.jpg
  static/images/platform/bitbucket_code_repo2.png
  static/images/platform/browser_chrome_view_sources.png
  static/images/platform/browser_chrome_webgl_inspector.jpg
  static/images/platform/dashboard_assets.png
  static/images/platform/dashboard_header_editor.png
  static/images/platform/dashboard_publish.png
  static/images/platform/design_view.png
  static/images/platform/design_view2.PNG
  static/images/platform/external_repo.jpg
  static/images/platform/localserver.png
  static/images/platform/playcanvas_code_repo.jpg
  static/images/platform/playcanvas_code_repo2.png
  static/images/platform/playcanvas_engine_architecture.jpg
  static/images/platform/playcanvas_repo.jpg
  static/images/platform/project_list.jpg
  static/images/platform/rotate-gizmo.PNG
  static/images/platform/scale-gizmo.PNG
  static/images/platform/scene_settings/scene_settings_gamma_correction.png
  static/images/platform/workflow/workflow_art.jpg
  static/images/platform/workflow/workflow_design.jpg
  static/images/platform/workflow/workflow_publish.jpg
  static/images/platform/workflow/workflow_scripting.jpg
  static/images/thumbnails/BMW_Thumb.png
  static/images/thumbnails/Orange_Thumb.png
  static/images/thumbnails/Robostorm_Thumb.png
  static/images/thumbnails/Rzr_Thumb.png
  static/images/thumbnails/Tanx_Thumb.png
  static/images/wireframe_logo.png
Labels: enhancement

#599 Move more images
  docs/tutorials/basic-cameras.md
  docs/user-manual/dashboard/header.md
  docs/user-manual/dashboard/index.md
  docs/user-manual/dashboard/overview.md
  docs/user-manual/profile/account.md
  docs/user-manual/profile/home.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/basic-cameras.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/dashboard/header.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/dashboard/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/dashboard/overview.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/profile/account.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/profile/home.md
  static/images/tutorials/basic-cameras/field-of-view.png
  static/images/user-manual/dashboard/dashboard-header.jpg
  static/images/user-manual/dashboard/dashboard-overview.png
  static/images/user-manual/dashboard/dashboard.png
  static/images/user-manual/frontpage/audio_tutorial_thumb.png
  static/images/user-manual/frontpage/input_tutorial_thumb.png
  static/images/user-manual/frontpage/keepy_up_tutorial_thumb.png
  static/images/user-manual/frontpage/physics_tutorial_thumb.png
  static/images/user-manual/frontpage/ui_tutorial_thumb.png
  static/images/user-manual/profile/account.png
  static/images/user-manual/profile/home.png
Labels: enhancement

#601 Add an Engine section
  .tx/config
  docs/user-manual/engine-only/index.md
  docs/user-manual/engine/index.md
  docs/user-manual/engine/standalone.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/changing-scenes.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/compound-physics-shapes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/standalone.md
  static/images/user-manual/engine/standalone/spinning-cube.webp
Labels: enhancement, docs

#602 Delete unreferenced images
  docs/user-manual/editor/toolbar.md
  docs/user-manual/optimization/runtime-devicepixelratio.md
  static/images/shader-editor/inspector-pane-project.png
  static/images/shader-editor/inspector-pane.png
  static/images/tutorials/audiosource_component.jpg
  static/images/tutorials/basic_audio_pack.jpg
  static/images/tutorials/beginner/cardboard-vr/script-component.jpg
  static/images/tutorials/beginner/cardboard-vr/script-priorities.jpg
  static/images/tutorials/beginner/cardboard-vr/script_loading_order.jpg
  static/images/tutorials/game.png
  static/images/tutorials/local.jpg
  static/images/tutorials/using_assets/error.jpg
  static/images/tutorials/using_assets/letters_script_attributed.jpg
  static/images/tutorials/webvr-ray-input/input-vr.jpg
  static/images/tutorials/webvr-ray-input/playcanvas-cube.jpg
  static/images/tutorials/webvr-ray-input/rotate-left.jpg
  static/images/tutorials/webvr-ray-input/shape-use-parent.jpg
  static/images/tutorials/world.jpg
  static/images/user-manual/assets/sprites/simple-sprite.jpg
  static/images/user-manual/graphics/lighting/lightmapping/point-bake.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio-disabled-thumb.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio-disabled.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio-enabled-thumb.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio-enabled.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio-setting.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio-thumb.jpg
  static/images/user-manual/optimization/device-pixel-ratio/device-pixel-ratio.jpg
  static/images/user-manual/publishing/web/kongregate/mceclip0.png
  static/images/user-manual/publishing/web/kongregate/mceclip1.png
  static/images/user-manual/publishing/web/make-zip.jpg
  static/images/user-manual/publishing/web/upload.jpg
  static/images/user-manual/scenes/load-scene-helper-script.png
  static/images/user-manual/scripting/attribute.jpg
  static/images/user-manual/scripting/code-editor-example-regex.png
  static/images/user-manual/user-interface/layout-groups/leaderboard-editor.jpg
  static/images/user-manual/user-interface/screens/mobile-landscape-blend-0.5.png
  static/images/user-manual/user-interface/screens/mobile-landscape-blend-0.png
  static/images/user-manual/user-interface/screens/mobile-landscape-blend-1.png
  static/images/user-manual/user-interface/screens/mobile-portrait-blend-0.5.png
  static/images/user-manual/user-interface/screens/mobile-portrait-blend-0.png
  static/images/user-manual/user-interface/screens/mobile-portrait-blend-1.png
  static/images/user-manual/version-control/merge-branches.jpg
  static/images/user-manual/version-control/vc-button.jpg
  static/images/user-manual/xr/ar-view.png
  static/images/user-manual/your-first-app/editor-camera-front.png
Labels: enhancement

#603 Updated tween code sample for onUpdate
  docs/tutorials/tweening.md
Labels: bug

#605 Fix rainbow trail tutorial link
  docs/tutorials/rainbow-trail-with-mesh-api.md
Labels: bug

#607 Create a Getting Started section
  .tx/config
  docs/user-manual/getting-started/creating-account.md
  docs/user-manual/getting-started/index.md
  docs/user-manual/getting-started/made-with-playcanvas.md
  docs/user-manual/getting-started/workflow.md
  docs/user-manual/getting-started/your-first-app.md
  docs/user-manual/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/tweening.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/getting-started/creating-account.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/getting-started/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/getting-started/made-with-playcanvas.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/getting-started/workflow.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/getting-started/your-first-app.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/index.md
  src/pages/index.js
Labels: enhancement, docs

#608 Add page on Real-time Collaboration
  docs/user-manual/editor/realtime-collaboration.md
  static/images/user-manual/editor/realtime-collaboration/chat.gif
  static/images/user-manual/editor/realtime-collaboration/presence-bar.png
  static/images/user-manual/editor/realtime-collaboration/selection-indicators.gif
  static/images/user-manual/editor/realtime-collaboration/selection-indicatorsx.gif
  static/images/user-manual/editor/realtime-collaboration/viewport-camera-username.png
  static/images/user-manual/editor/realtime-collaboration/viewport-cameras.webp
  static/images/user-manual/editor/realtime-collaboration/viewport-selection.gif
Labels: enhancement, docs

#606 Add documentation for 3D Gaussian Splatting
  docs/user-manual/assets/types/gsplat.md
  docs/user-manual/assets/types/index.md
  docs/user-manual/graphics/gaussian-splatting.md
  docs/user-manual/scenes/components/gsplat.md
  static/images/user-manual/assets/types/asset-inspector-gsplat.png
  static/images/user-manual/graphics/gaussian-splatting/import-gsplat.webp
  static/images/user-manual/graphics/gaussian-splatting/supersplat.png
  static/images/user-manual/scenes/components/component-gsplat.png
Labels: enhancement, docs

#609 WebXR - image tracking user manual
  docs/user-manual/xr/ar/image-tracking.md
  docs/user-manual/xr/capabilities.md
Labels: enhancement, docs

#611 Add documentation on the Asset Store
  docs/user-manual/assets/asset-store.md
  docs/user-manual/assets/asset-store/index.md
  docs/user-manual/assets/asset-store/sketchfab.md
  static/images/user-manual/assets/asset-store/asset-store-button.png
  static/images/user-manual/assets/asset-store/asset-store-details.png
  static/images/user-manual/assets/asset-store/asset-store-search.png
  static/images/user-manual/assets/asset-store/asset-store.png
  static/images/user-manual/assets/asset-store/sketchfab-authorization.png
  static/images/user-manual/assets/asset-store/sketchfab-login.png
  static/images/user-manual/assets/asset-store/sketchfab-store.png
Labels: enhancement, docs

#614 Update Japanese translations
  .tx/config
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/asset-store/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/asset-store/sketchfab.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/types/gsplat.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/dashboard/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/realtime-collaboration.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/toolbar.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/gaussian-splatting.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/profile/projects.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/components/gsplat.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/user-interface/image-elements.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/user-interface/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/user-interface/input.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/user-interface/localization.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/image-tracking.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/light-estimation.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/mesh-detection.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/ar/plane-detection.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/capabilities.md
Labels: docs, translation

#615 Localize the front page to Japanese
  i18n/ja/code.json
  i18n/ja/docusaurus-plugin-content-docs/current.json
  i18n/ja/docusaurus-theme-classic/footer.json
  i18n/ja/docusaurus-theme-classic/navbar.json
  src/components/HomepageFeatures/index.js
  src/pages/index.js
Labels: enhancement

#616 Physics section tidy up
  docs/user-manual/physics/ammo-alternatives.md
  docs/user-manual/physics/calling-ammo.md
  docs/user-manual/physics/compound-shapes.md
  docs/user-manual/physics/physics-basics.md
  docs/user-manual/physics/physics-migration.md
  docs/user-manual/physics/ray-casting.md
  docs/user-manual/physics/trigger-volumes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/physics/compound-shapes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/physics/physics-basics.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/physics/physics-migration.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/physics/ray-casting.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/physics/trigger-volumes.md
Labels: enhancement

#617 Automatically crawl the site with Algolia after deploy
  .github/workflows/deploy.yml
Labels: enhancement

#620 Inline more image references
  docs/tutorials/google-ads-for-games.md
  docs/tutorials/importing-first-model-and-animation.md
  docs/tutorials/touch-joypad.md
  docs/tutorials/ui-text-input.md
  docs/user-manual/2D/texture-packing.md
  docs/user-manual/assets/import-pipeline/import-hierarchy.md
  docs/user-manual/assets/models/exporting.md
  docs/user-manual/assets/types/animation.md
  docs/user-manual/assets/viewers.md
  docs/user-manual/editor/editor-api.md
  docs/user-manual/graphics/lighting/clustered-lighting.md
  docs/user-manual/press-pack.md
  docs/user-manual/scripting/code-editor.md
  docs/user-manual/version-control/checkpoints.md
  docs/user-manual/version-control/graph-view.md
  docs/user-manual/version-control/item-history.md
Labels: enhancement

#626 Latest from Transifex
  i18n/ja/docusaurus-plugin-content-docs/current/shader-editor/introduction.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/crash-course.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/custom-shaders.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/google-ads-for-games.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/importing-first-model-and-animation.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/keepyup-part-four.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/keepyup-part-six.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/real-time-multiplayer-colyseus.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/real-time-multiplayer-photon.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/real-time-multiplayer.md
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/ui-elements-buttons.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/api/asset-create.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/api/asset-update.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/models/building.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/types/cubemap.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/types/texture-atlas.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/getting-started/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/glossary.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/advanced-rendering/hardware-instancing.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/layers/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/lighting/clustered-lighting.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/lighting/runtime-lightmaps.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/graphics/shader-chunk-migrations.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/optimization/runtime-devicepixelratio.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/mobile/cordova.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/playable-ads/fb-playable-ads.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/playable-ads/ironsource-mraid-playable-ads.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/playable-ads/snapchat-playable-ads.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/web/self-hosting-for-beginners.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/loading-scenes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/templates/index.md
Labels: translation

#627 Add support for markdownlint-cli2
  .github/workflows/ci.yml
  .github/workflows/test-deploy.yml
  .markdownlint-cli2.yaml
  README.md
  package-lock.json
  package.json
Labels: enhancement

#630 Rewrite loading screen page
  docs/tutorials/advance-loading-screen.md
  docs/user-manual/editor/launch-page/loading-screen.md
  static/img/user-manual/editor/launch-page/loading-screen/loading-screen-default.webp
  static/img/user-manual/editor/launch-page/loading-screen/loading-screen-settings.png
  static/img/user-manual/editor/loading-screen/loading-screen.png
Labels: enhancement, docs
