Repository playcanvas/developer-site, pull requests merged in 2025-01, with the labels that each got.

#684 Add user guide pages for Engine Web Components
  docs/user-manual/engine/web-components/getting-started.md
  docs/user-manual/engine/web-components/index.md
  docs/user-manual/engine/web-components/tags/index.md
  docs/user-manual/engine/web-components/tags/pc-app.md
  docs/user-manual/engine/web-components/tags/pc-asset.md
  docs/user-manual/engine/web-components/tags/pc-camera.md
  docs/user-manual/engine/web-components/tags/pc-collision.md
  docs/user-manual/engine/web-components/tags/pc-element.md
  docs/user-manual/engine/web-components/tags/pc-entity.md
  docs/user-manual/engine/web-components/tags/pc-light.md
  docs/user-manual/engine/web-components/tags/pc-listener.md
  docs/user-manual/engine/web-components/tags/pc-module.md
  docs/user-manual/engine/web-components/tags/pc-render.md
  docs/user-manual/engine/web-components/tags/pc-rigidbody.md
  docs/user-manual/engine/web-components/tags/pc-scene.md
  docs/user-manual/engine/web-components/tags/pc-screen.md
  docs/user-manual/engine/web-components/tags/pc-script.md
  docs/user-manual/engine/web-components/tags/pc-scripts.md
  docs/user-manual/engine/web-components/tags/pc-sky.md
  docs/user-manual/engine/web-components/tags/pc-sound.md
  docs/user-manual/engine/web-components/tags/pc-sounds.md
  docs/user-manual/engine/web-components/tags/pc-splat.md
Labels: enhancement

#685 Use angled brackets around tag names
  docs/user-manual/engine/web-components/tags/pc-app.md
  docs/user-manual/engine/web-components/tags/pc-asset.md
  docs/user-manual/engine/web-components/tags/pc-camera.md
  docs/user-manual/engine/web-components/tags/pc-collision.md
  docs/user-manual/engine/web-components/tags/pc-element.md
  docs/user-manual/engine/web-components/tags/pc-entity.md
  docs/user-manual/engine/web-components/tags/pc-light.md
  docs/user-manual/engine/web-components/tags/pc-listener.md
  docs/user-manual/engine/web-components/tags/pc-module.md
  docs/user-manual/engine/web-components/tags/pc-render.md
  docs/user-manual/engine/web-components/tags/pc-rigidbody.md
  docs/user-manual/engine/web-components/tags/pc-scene.md
  docs/user-manual/engine/web-components/tags/pc-screen.md
  docs/user-manual/engine/web-components/tags/pc-script.md
  docs/user-manual/engine/web-components/tags/pc-scripts.md
  docs/user-manual/engine/web-components/tags/pc-sky.md
  docs/user-manual/engine/web-components/tags/pc-sound.md
  docs/user-manual/engine/web-components/tags/pc-sounds.md
  docs/user-manual/engine/web-components/tags/pc-splat.md
Labels: enhancement

#688 Web Components: Add CodePen embeds
  docs/user-manual/engine/web-components/tags/pc-app.md
  docs/user-manual/engine/web-components/tags/pc-asset.md
  docs/user-manual/engine/web-components/tags/pc-camera.md
  docs/user-manual/engine/web-components/tags/pc-collision.md
  docs/user-manual/engine/web-components/tags/pc-element.md
  docs/user-manual/engine/web-components/tags/pc-entity.md
  docs/user-manual/engine/web-components/tags/pc-light.md
  docs/user-manual/engine/web-components/tags/pc-module.md
  docs/user-manual/engine/web-components/tags/pc-render.md
  docs/user-manual/engine/web-components/tags/pc-rigidbody.md
  docs/user-manual/engine/web-components/tags/pc-scene.md
  docs/user-manual/engine/web-components/tags/pc-screen.md
  docs/user-manual/engine/web-components/tags/pc-script.md
  docs/user-manual/engine/web-components/tags/pc-scripts.md
  docs/user-manual/engine/web-components/tags/pc-sky.md
  docs/user-manual/engine/web-components/tags/pc-sound.md
  docs/user-manual/engine/web-components/tags/pc-sounds.md
  docs/user-manual/engine/web-components/tags/pc-splat.md
  src/components/CodePenEmbed/index.js
Labels: enhancement

#689 Move Engine before Editor
  docs/user-manual/2D/index.md
  docs/user-manual/animation/index.md
  docs/user-manual/api/index.md
  docs/user-manual/assets/index.md
  docs/user-manual/billing/index.md
  docs/user-manual/dashboard/index.md
  docs/user-manual/editor/index.md
  docs/user-manual/engine/index.md
  docs/user-manual/faq.md
  docs/user-manual/glossary.md
  docs/user-manual/graphics/index.md
  docs/user-manual/optimization/index.md
  docs/user-manual/organizations/index.md
  docs/user-manual/physics/index.md
  docs/user-manual/press-pack.md
  docs/user-manual/profile/index.md
  docs/user-manual/publishing/index.md
  docs/user-manual/scenes/index.md
  docs/user-manual/scripting/index.md
  docs/user-manual/templates/index.md
  docs/user-manual/user-interface/index.md
  docs/user-manual/version-control/index.md
  docs/user-manual/xr/index.md
Labels: enhancement

#690 Move Version Control section under Editor
  .tx/config
  docs/user-manual/api/index.md
  docs/user-manual/editor/version-control/branch-workflows.md
  docs/user-manual/editor/version-control/branches.md
  docs/user-manual/editor/version-control/changes.md
  docs/user-manual/editor/version-control/checkpoints.md
  docs/user-manual/editor/version-control/graph-view.md
  docs/user-manual/editor/version-control/index.md
  docs/user-manual/editor/version-control/item-history.md
  docs/user-manual/editor/version-control/merging.md
  docusaurus.config.js
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/api/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/branch-workflows.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/branches.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/changes.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/checkpoints.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/graph-view.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/item-history.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/version-control/merging.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/running-in-node.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/getting-started.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-app.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-asset.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-camera.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-collision.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-element.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-entity.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-light.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-listener.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-module.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-render.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-rigidbody.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-scene.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-screen.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-script.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-scripts.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-sky.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-sound.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-sounds.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/engine/web-components/tags/pc-splat.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/optimization/gpu-profiling.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/web/hosting-heyvr.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/publishing/web/self-hosting.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scripting/vscode-extension.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/xr/platforms.md
Labels: enhancement

#692 Move Templates section under Editor
  .tx/config
  README.md
  docs/tutorials/touch-joypad.md
  docs/user-manual/assets/import-pipeline/import-hierarchy.md
  docs/user-manual/assets/models/index.md
  docs/user-manual/assets/types/template.md
  docs/user-manual/editor/templates/diff.md
  docs/user-manual/editor/templates/index.md
  docs/user-manual/editor/templates/nested.md
  docs/user-manual/optimization/load-time.md
  docs/user-manual/scenes/loading-scenes.md
  docusaurus.config.js
  i18n/ja/docusaurus-plugin-content-docs/current/tutorials/touch-joypad.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/import-pipeline/import-hierarchy.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/models/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/assets/types/template.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/templates/diff.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/templates/index.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/editor/templates/nested.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/optimization/load-time.md
  i18n/ja/docusaurus-plugin-content-docs/current/user-manual/scenes/loading-scenes.md
Labels: enhancement

#687 New page for engine v1 to v2 migration
  docs/user-manual/engine/migrations.md
Labels: enhancement

#694 Add PCUI docs
  docs/user-manual/pcui/api-reference.md
  docs/user-manual/pcui/data-binding/index.md
  docs/user-manual/pcui/data-binding/two-way-binding.md
  docs/user-manual/pcui/data-binding/using-observers.md
  docs/user-manual/pcui/examples/history.md
  docs/user-manual/pcui/examples/index.md
  docs/user-manual/pcui/examples/todo-list.md
  docs/user-manual/pcui/getting-started.md
  docs/user-manual/pcui/index.md
  docs/user-manual/pcui/pcui-graph.md
  docs/user-manual/pcui/react.md
  docs/user-manual/pcui/storybook.md
  static/img/user-manual/pcui/pcui-banner.jpg
Labels: docs

#696 Add docs for pc-model tag
  docs/user-manual/engine/web-components/tags/pc-entity.md
  docs/user-manual/engine/web-components/tags/pc-model.md
  docs/user-manual/engine/web-components/xr.md
Labels: enhancement, docs

#697 Web Components: Add a page on building a scene
  docs/user-manual/engine/web-components/building-a-scene.md
Labels: enhancement, docs

#691 Editor documentation for Engine V2
  docs/user-manual/editor/editor-migrations.md
  docs/user-manual/editor/engine-compatibility.md
  static/img/user-manual/editor/editor-v2/console-texture.png
  static/img/user-manual/editor/editor-v2/edge-filter.png
  static/img/user-manual/editor/editor-v2/gamma-compare.png
  static/img/user-manual/editor/editor-v2/gamma-tonemap-settings.png
  static/img/user-manual/editor/editor-v2/gamma-tonemap.png
  static/img/user-manual/editor/editor-v2/launcher-options.png
  static/img/user-manual/editor/editor-v2/prefiltered-data.png
  static/img/user-manual/editor/editor-v2/scripting-engine.png
  static/img/user-manual/editor/editor-v2/srgb-texture.png
  static/img/user-manual/editor/editor-v2/switch-engine.png
  static/img/user-manual/editor/editor-v2/viewport-camera.png
Labels: enhancement

#699 Web Components: Add scripting guide
  docs/user-manual/engine/web-components/scripting.md
  docs/user-manual/engine/web-components/tags/index.md
  docs/user-manual/engine/web-components/xr.md
Labels: enhancement

#700 Engine v2 migration - added info on instancing changes
  docs/user-manual/engine/migrations.md
Labels: enhancement, docs
