Repository playcanvas/developer-site, pull requests merged in 2025-03, with the labels that each got.

#711 Bring chunk migration page for engine 2.6 up to date
  docs/user-manual/graphics/shader-chunk-migrations.md
Labels: docs

#712 Updated chunk migration for engine 2.6
  docs/user-manual/graphics/shader-chunk-migrations.md
Labels: docs

#713 Updated chunk migration to be up to date with the engine changes
  docs/user-manual/graphics/shader-chunk-migrations.md
Labels: docs

#715 Add docs for pc-particles element
  docs/user-manual/engine/web-components/tags/index.md
  docs/user-manual/engine/web-components/tags/pc-particles.md
Labels: enhancement

#714 shadowSampleCoordPS chunk migration
  docs/user-manual/graphics/shader-chunk-migrations.md
Labels: docs

#721 Update shader.md
  docs/user-manual/assets/types/shader.md
Labels: bug

#724 Update links to updated API Reference location
  docs/shader-editor/window-layout/inspector-pane/material-inspector.md
  docs/tutorials/Using-forces-on-rigid-bodies.md
  docs/tutorials/audio-effects.md
  docs/tutorials/collision-and-triggers.md
  docs/tutorials/controlling-lights.md
  docs/tutorials/custom-shaders.md
  docs/tutorials/entity-picking.md
  docs/tutorials/first-person-movement.md
  docs/tutorials/light-halos.md
  docs/tutorials/music-visualizer.md
  docs/tutorials/procedural-levels.md
  docs/tutorials/terrain-generation.md
  docs/tutorials/touch-joypad.md
  docs/tutorials/ui-elements-buttons.md
  docs/tutorials/ui-elements-progress.md
  docs/tutorials/using-assets.md
  docs/tutorials/webxr-ray-input.md
  docs/user-manual/assets/import-pipeline/import-hierarchy.md
  docs/user-manual/editor/editor-api.md
  docs/user-manual/editor/interface/assets.md
  docs/user-manual/glossary.md
  docs/user-manual/graphics/advanced-rendering/batching.md
  docs/user-manual/graphics/advanced-rendering/hardware-instancing.md
  docs/user-manual/graphics/cameras/depth-layer.md
  docs/user-manual/graphics/lighting/clustered-lighting.md
  docs/user-manual/graphics/linear-workflow/hdr-rendering.md
  docs/user-manual/graphics/particles.md
  docs/user-manual/graphics/shaders/index.md
  docs/user-manual/optimization/guidelines.md
  docs/user-manual/optimization/runtime-devicepixelratio.md
  docs/user-manual/pcui/getting-started.md
  docs/user-manual/pcui/pcui-graph/events.md
  docs/user-manual/pcui/pcui-graph/getting-started.md
  docs/user-manual/physics/forces-and-impulses.md
  docs/user-manual/scenes/components/animation.md
  docs/user-manual/scenes/components/audiolistener.md
  docs/user-manual/scenes/components/button.md
  docs/user-manual/scenes/components/camera.md
  docs/user-manual/scenes/components/collision.md
  docs/user-manual/scenes/components/gsplat.md
  docs/user-manual/scenes/components/layout-child.md
  docs/user-manual/scenes/components/layout-group.md
  docs/user-manual/scenes/components/light.md
  docs/user-manual/scenes/components/model.md
  docs/user-manual/scenes/components/particlesystem.md
  docs/user-manual/scenes/components/render.md
  docs/user-manual/scenes/components/rigidbody.md
  docs/user-manual/scenes/components/script.md
  docs/user-manual/scenes/components/sound.md
  docs/user-manual/scenes/components/sprite.md
  docs/user-manual/scenes/loading-scenes.md
  docs/user-manual/scripting/communication.md
  docs/user-manual/scripting/creating-new.md
  docs/user-manual/scripting/script-attributes.md
  docs/user-manual/user-interface/localization.md
  docs/user-manual/xr/hand-tracking.md
  docs/user-manual/xr/input-sources.md
  docs/user-manual/xr/using-webxr.md
  docs/user-manual/xr/vr/types-of-vr.md
Labels: enhancement

#705 Engine compatibility - Advise checkpoint usage
  docs/user-manual/editor/engine-compatibility.md
Labels: enhancement

#725 Fix call to Mat4#setTRS in sample code
  docs/user-manual/graphics/advanced-rendering/hardware-instancing.md
Labels: bug
